apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: sapna350/springboot-app:latest
          ports:
            - containerPort: 8080
